package: milestone
version: '2.0.0'
author: 'Paul Götz, Alexander Walther'
supportpage: https://github.com/alexplusde/milestone


requires:
    php:
        version: '^8.2'
    redaxo: ^5.16
    packages:
        yform/manager: '^4'
        yform_field: '^2.5.0'

page:
    title: translate:milestone
    icon: rex-icon fa-gem
    block: system
    prio: 19
    subpages:
        entry:
            title: translate:milestone_entry
            icon: rex-icon fa-gem
            perm: milestone[]
#            settings:
#                title: translate:milestone_settings
#                icon: rex-icon fa-gear
#                itemclass: pull-right
#                perm: admin
        docs:
            title: translate:milestone_docs
            subPath: README.md
            icon: rex-icon fa-info-circle
            itemclass: pull-right
            perm: milestone[docs]
